# Generated by Django 3.2.20 on 2023-09-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearlist',
            name='items',
        ),
        migrations.AddField(
            model_name='gearlist',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_wu5uso', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='GearItem',
        ),
    ]
