# Generated by Django 3.2.20 on 2023-09-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearlists', '0002_auto_20230901_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearlist',
            name='listtype',
            field=models.CharField(choices=[('bike', 'Bike'), ('climbing', 'Climbing'), ('hiking', 'Hiking')], default='bike', max_length=20),
        ),
    ]
