# Generated by Django 3.2.20 on 2023-09-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearlists', '0003_gearlist_listtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearlist',
            name='listtype',
            field=models.CharField(choices=[('bike', 'Bike'), ('climbing', 'Climbing'), ('hiking', 'Hiking'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
