# Generated by Django 3.2.20 on 2023-09-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearlists', '0005_alter_gearlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gearlist',
            old_name='listtype',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='gearlist',
            name='image',
            field=models.ImageField(blank=True, default='../other_ustsrk.jpg', upload_to='images/'),
        ),
    ]
